name: Main

on:
  schedule:
    - cron: "0 1 * * *" # 6:30am IST
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: install requirements
        run: pip install -r scraper/requirements.txt

      - name: run github scraper
        run: python scraper/src/github.py coronasafe data/github -l DEBUG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: run slack scraper
        run: python scraper/src/slack.py --lookback_days=2
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --staged --quiet || git commit -am "🌍 Update JSON - $(date -d '+5 hours +30 minutes' +'%d %b %Y | %I:%M %p')"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
