name: Scraper Dry Run

on:
  pull_request:
    paths:
      - scraper/**

jobs:
  test-run-github-scraper:
    name: Test run GitHub Scraper
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.14.0"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: scraper

      - name: Build the project
        run: pnpm build
        working-directory: scraper

      - name: Scrape data from GitHub
        run: pnpm start ${{ github.repository_owner }} data/github 
        working-directory: scraper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify scraper output
        run: ls -l ../data-repo/data/github

      - name: Generate markdown files for new contributors
        run: node ../scripts/generateNewContributors.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify generated markdown files
        run: ls -l ../data-repo/contributors
        
      - uses: actions/upload-artifact@v4
        with:
          name: output
          retention-days: 5
          path: |
            data
            contributors
