name: Scraper Dry Run & Validate Schema

on:
  workflow_dispatch:
  pull_request:
    paths:
      - scraper/**
      - tests/**
      - schemas/**

jobs:
  test-run-github-scraper:
    name: Test run GitHub Scraper
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull_requests: read
    env:
      DATA_REPO: ./
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and PNPM
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: scraper

      - name: Build the project
        run: pnpm build
        working-directory: scraper

      - name: Scrape data from GitHub
        run: pnpm start ${{ github.repository_owner }} ../data/github 
        working-directory: scraper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: mkdir contributors

      - name: Generate markdown files for new contributors
        run: node scripts/generateNewContributors.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: output
          retention-days: 5
          path: |
            data
            contributors

      - name: Setup PNPM cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          key: ${{ runner.os }}-pnpm-store-
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Run Tests
        run: pnpm test
